version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"  # Host port 5000 -> Container port 5000
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - redis
    command: python main.py

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"  # Expose Redis on port 6379
